[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    -s

markers =
    collection: запустить всю коллекцию тестов
    create_and_delete_folder: создание и удаление папки
    upload_and_delete_file: загрузка и удаление файла
    trash_delete_and_restore: удаление и восстановление файла
    replace_file: перемещение файла в другую папку
